### PR TITLE
Small doc fix in getting started. Make sure text matches example.

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes elastic/logstash#2687 . Make text match example

### CODE REVIEW

**Comment by jordansissel** [comment]
This also affects other docs (1.4.3, etc).

The origin of the docs is in the logstash repo itself: https://github.com/elastic/logstash/blob/1.4/docs/tutorials/getting-started-with-logstash.asciidoc

The files here in docs/x.y.z/... are all generated by the docs generator from the logstash repo (complicated, sorry about that).

I'm +1 on merging this, but can you update all 1.4.x's as well as the origin data in the 1.4 branch on elastic/logstash?

**Comment by andrewvc** [comment]
@jordansissel not a problem. They're all updated. Is just the .md file correct? I'm assuming the others are autogenerated by a build process somewhere?

**Comment by andrewvc** [comment]
Ok, now fixed in asciidocs as well.

**Comment by jordansissel** [comment]
LGTM! <3

**Pull request merged**
